const fs = require("fs/promises");
const path = require("path");
const { createReport } = require("docx-templates");

const pipClinics = [
  "quantum chiropractic", "total injury", "good health medical",
  "naples family health", "advanced wellness", "a1 medical",
  "441 chiropractic", "pompano beach healing", "brofsky accident",
  "renewed health", "grassam family", "spine & extremity",
  "flex medical", "med plus", "bentin", "tropical chiropractic",
  "mohammad t. javed", "florida orthopedic", "shree mri", "revive chiropractic",
  "tamarac chiropractic", "sunlight chiropractic", "dr. craig selinger",
  "margate medical", "napoli chiropractic", "behnam meyers", "glenn v. quintana",
  "advanced orthopedics", "amos", "gady abramson", "back to mind", "premier wellness"
];

function isPipClinicMatch(providerName = "") {
  const name = providerName.toLowerCase();
  return pipClinics.some(clinic => name.includes(clinic));
}

async function generateDemandLetterBuffer(structuredData = {}, options = {}) {
  // 🟡 Try to parse raw_text if it exists
  if (structuredData.raw_text) {
    try {
      const match = structuredData.raw_text.match(/```json\s*([\s\S]+?)\s*```|({[\s\S]+})/);
      const jsonStr = match?.[1] || match?.[0];
      if (jsonStr) {
        structuredData = JSON.parse(jsonStr.trim());
      }
    } catch (err) {
      console.warn("⚠️ Failed to parse raw_text in generateDemandLetterBuffer:", err);
    }
  }

  const {
    "Claimant Name": name,
    "Insured Name": insuredName,
    "Provider": provider,
    "Claim Number": claimNumber,
    "Insurance Company": insuranceCompany,
    "Dates of Service": dos,
    "Bill Amount": billAmount,
  } = structuredData;

  const replacements = {
    currentDate: new Date().toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    }),
    name: name || "N/A",
    insuredName: insuredName || "N/A",
    provider: provider || "N/A",
    claimNumber: claimNumber || "N/A",
    insuranceCompany: insuranceCompany || "N/A",
    serviceDates: Array.isArray(dos) ? dos.join(" - ") : (dos || "N/A"),
    billAmount: `$${(parseFloat(String(billAmount)) || 0).toFixed(2)}`
  };

  // ✅ HTML preview
  if (options.asHtml) {
    return `
      <div>
        <h2 style="margin-bottom: 1rem;">Demand Letter Preview</h2>
        <p><strong>Date:</strong> ${replacements.currentDate}</p>
        <p><strong>Claimant:</strong> ${replacements.name}</p>
        <p><strong>Insured:</strong> ${replacements.insuredName}</p>
        <p><strong>Provider:</strong> ${replacements.provider}</p>
        <p><strong>Claim #:</strong> ${replacements.claimNumber}</p>
        <p><strong>Insurance Company:</strong> ${replacements.insuranceCompany}</p>
        <p><strong>Service Dates:</strong> ${replacements.serviceDates}</p>
        <p><strong>Bill Amount:</strong> ${replacements.billAmount}</p>
        <hr />
        <p>This demand letter was automatically generated by ClaimClarity AI. It may require review by legal counsel.</p>
      </div>
    `;
  }

  const useTemplate2 = isPipClinicMatch(provider);
  const templatePath = path.join(
    __dirname,
    "..",
    "assets",
    useTemplate2 ? "2.0_letter_template.docx" : "1.0_LETTER_TEMPLATE.docx"
  );

  const templateBuffer = await fs.readFile(templatePath);

  const docBuffer = await createReport({
    template: templateBuffer,
    data: {
      "«current_date_long»": replacements.currentDate,
      "«Plaintiff_full_name»": replacements.name,
      "«Defendant_Insurance_Co_insured»": replacements.insuredName,
      "«Clinic_company_sk»": replacements.provider,
      "«Defendant_Insurance_Co_claim_number»": replacements.claimNumber,
      "«matter_number»": `AUTO-GEN-${Date.now()}`,
      "«Defendant_Insurance_Co_company_sk»": replacements.insuranceCompany,
      "«service_date_range»": replacements.serviceDates,
      "«bill_amount»": replacements.billAmount,
    },
  });

  return docBuffer;
}


module.exports = generateDemandLetterBuffer;
